In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("SUM\n", np.sum(arr))
print("mean \n",np.mean(arr))
print("median \n",np.median(arr))
print("standard values \n",np.std(arr))
print("variance values \n", np.var(arr))
print("min values \n", np.min(arr))
print("min values \n", np.max(arr))


SUM
 15
mean 
 3.0
median 
 3.0
standard values 
 1.4142135623730951
variance values 
 2.0
min values 
 1
min values 
 5


In [3]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.sum(arr, axis=0))  # [5 7 9]   (column-wise sum)
print(np.sum(arr, axis=1))  # [ 6 15]   (row-wise sum)

print(np.mean(arr, axis=0)) # [2.5 3.5 4.5]
print(np.mean(arr, axis=1)) # [2.0 5.0]

print(np.max(arr, axis=0))  # [4 5 6]
print(np.min(arr, axis=1))  # [1 4]


[5 7 9]
[ 6 15]
[2.5 3.5 4.5]
[2. 5.]
[4 5 6]
[1 4]
