# import library

In [7]:
import numpy as np

In [8]:
# DATA STRUCTURE: [restaurant_id, 2021, 2022, 2023, 2024]

sales_data = np.array([
    [1, 150000, 180000,220000,250000],
    [2, 120000,140000,160000,190000],
    [3,200000, 230000,260000, 300000],
    [4,180000,210000,240000,270000],
    [5,160000,185000, 205000,230000]
])

print("=== Zomato === sales === data ===")



=== Zomato === sales === data ===


In [11]:
print(sales_data.shape)   # rows, columns
print(sales_data.ndim)    # number of dimensions
print(sales_data.size)    # total elements
print(sales_data.dtype)   # data type


(5, 5)
2
25
int64


In [10]:
print("sales data first three: ", sales_data[0:3])

sales data first three:  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


# Indexing & Slicing

In [12]:
# Get the first row
print(sales_data[0])

# Get the first column (IDs)
print(sales_data[:, 0])

# Get sales of Q1 for all products
print(sales_data[:, 1])

# Sales of product 3 across all quarters
print(sales_data[2, 1:])


[     1 150000 180000 220000 250000]
[1 2 3 4 5]
[150000 120000 200000 180000 160000]
[200000 230000 260000 300000]


# Aggregations

In [13]:
# Total sales for each product
print(np.sum(sales_data[:, 1:], axis=1))

# Average sales per quarter
print(np.mean(sales_data[:, 1:], axis=0))

# Maximum sales overall
print(np.max(sales_data[:, 1:]))

# Which product had the highest total sales?
total_sales = np.sum(sales_data[:, 1:], axis=1)
print(np.argmax(total_sales) + 1)   # +1 for product ID


[800000 610000 990000 900000 780000]
[162000. 189000. 217000. 248000.]
300000
3
